class ItemAlreadyExistsError(Exception):
    pass


class ItemNotFoundError(Exception):
    pass